Add PersistentVolumeClaims for IPsec VPN Server
taskmedia/helm_ipsec-vpn-server pull request #19
Opened 2024-06-05 11:59 UTC by nikolaigut

This pull request adds PersistentVolumeClaims (PVCs) to the IPsec VPN Server chart to provide persistent storage for configuration and data volumes. This allows for the persistence of configuration data and IPsec-related data across pod restarts.

2024-09-20 13:16 UTC, fty4 requested changes
Sorry for the late response..

I think we do not need 1 GB of PVC here - i guess 10 MB should be way enought!

```bash
vpn-vpn-server-57b97b9564-hvl2z:~# du -sh /opt/src/env/
12K	/opt/src/env/
vpn-vpn-server-57b97b9564-hvl2z:~# du -sh /etc/ipsec.d/
104K	/etc/ipsec.d/
```

I agree to persist the `ipsec-data` volume but do not really get the point for persisting the `vpn-config` volume. This volume will always be regenerated in the initContainer. Therefore it should not be persisted, right?

2024-09-20 13:16 UTC, fty4 commented on charts/ipsec-vpn-server/templates/pvc.yaml
> +          storage: 1Gi
```suggestion
          storage: 10Mi
```

2024-09-20 13:16 UTC, fty4 commented on charts/ipsec-vpn-server/templates/pvc.yaml
> +          storage: 1Gi
```suggestion
          storage: 10Mi

```

2024-10-08 19:09 UTC, fty4 commented
@nikolaigut This question is still open:

> I agree to persist the `ipsec-data` volume but do not really get the point for persisting the `vpn-config` volume. This volume will always be regenerated in the initContainer. Therefore it should not be persisted, right?

I guess we will not require the persistence for the data `ipsec-data` volume. Do you agree?

2024-10-09 04:09 UTC, nikolaigut commented
@fty4 I agree with you that the config directory does not need to be persisted

2024-10-09 09:29 UTC, fty4 approved these changes

2024-10-09 09:38 UTC, merged